# I love documentation that ships with a Makefile...

default:
	epstopdf ELF-Format.eps
	epstopdf System-call.eps
	epstopdf cache-mech.eps
	latex digsig.tex
	pdflatex digsig.tex

clean:
	rm -f *.aux *.dvi *.log *.pdf *.ps


